version: '3.8'

services:
  camagru: 
    build:
      dockerfile: Dockerfile
      context: .
    command: npm start
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MONGO_URL: ${MONGO_URL}
    ports:
      - 3000:3000
    restart: always


 